// =============================================================================
// q7 - Pulse Synchronizer (Clock Domain Crossing) -- Testbench
// =============================================================================
// Problem:
//   src_pulse is a single-src_clk-cycle pulse generated in the source clock
//   domain (src_clk). Design a circuit that safely crosses this pulse into
//   an independent, asynchronous destination clock domain (dst_clk),
//   producing a corresponding single-dst_clk-cycle pulse dst_pulse.
//
//   HINT: the standard, robust technique for this is "toggle + double-flop
//   synchronizer + edge detect":
//     1. In the src_clk domain, toggle a flip-flop each time src_pulse fires.
//     2. Synchronize that toggle signal into the dst_clk domain with a
//        2-flop (or more) synchronizer chain to avoid metastability.
//     3. Edge-detect the synchronized toggle signal (XOR it with a
//        one-cycle-delayed version of itself) in the dst_clk domain to
//        produce a single-cycle dst_pulse.
//
// Interface:
//   input  logic src_clk    : source domain clock
//   input  logic src_rst    : source domain synchronous active-high reset
//   input  logic src_pulse  : single src_clk-cycle-wide pulse, source domain
//   input  logic dst_clk    : destination domain clock (independent, async)
//   input  logic dst_rst    : destination domain synchronous active-high reset
//   output logic dst_pulse  : single dst_clk-cycle-wide pulse, destination domain
//
// Assumptions / edge-case behavior:
//   - src_rst and dst_rst are each synchronous to their own clock and are
//     asserted/deasserted independently by the testbench.
//   - On reset (in either domain), that domain's registers reset such that
//     no spurious dst_pulse is produced.
//   - DOCUMENTED ASSUMPTION: consecutive src_pulse events are spaced at
//     least ~3 dst_clk periods apart, so the synchronizer never has to
//     absorb two source pulses before the previous one has been observed
//     in the destination domain (otherwise pulses could be lost/coalesced,
//     which is a fundamental limitation of this class of synchronizer, not
//     a bug to fix here).
//   - Every asserted src_pulse eventually produces exactly one dst_pulse
//     (given the spacing assumption above); no extra/missing dst_pulse.
//
// Verification strategy: two independent free-running clocks with different,
// non-integer-multiple periods (src_clk = 7ns, dst_clk = 13ns). Each domain
// is reset independently at the start. A randomized sequence of src_pulse
// pulses (each exactly 1 src_clk cycle wide) is driven, respecting the
// minimum spacing assumption. Self-check is done by COUNTING: total number
// of src_pulse assertions must equal total number of dst_pulse assertions
// observed by the end of the test (after a settle/drain period following the
// last src_pulse, to allow for CDC latency). This is the correct way to
// self-check a pulse synchronizer since exact cycle-accurate correspondence
// is not deterministic across an async CDC boundary. Do not edit this file.
// =============================================================================

module q7_tb;

    logic src_clk, src_rst, src_pulse;
    logic dst_clk, dst_rst, dst_pulse;

    int errors    = 0;
    int src_count = 0;
    int dst_count = 0;

    q7 dut (
        .src_clk   (src_clk),
        .src_rst   (src_rst),
        .src_pulse (src_pulse),
        .dst_clk   (dst_clk),
        .dst_rst   (dst_rst),
        .dst_pulse (dst_pulse)
    );

    // Two independent, non-integer-multiple-period free-running clocks.
    initial src_clk = 0;
    always #3.5 src_clk = ~src_clk;   // 7ns period

    initial dst_clk = 0;
    always #6.5 dst_clk = ~dst_clk;   // 13ns period

    // Watchdog
    initial begin
        #200000;
        $display("TEST FAILED: TIMEOUT");
        $finish;
    end

    // Count dst_pulse assertions, entire run.
    always @(posedge dst_clk) begin
        if (dst_pulse) begin
            dst_count++;
            if (dst_rst) begin
                errors++;
                $display("T=%0t ERROR: dst_pulse asserted while dst_rst is high", $time);
            end
        end
    end

    // Independent reset for destination domain: hold for first few dst_clk edges.
    initial begin
        dst_rst = 1;
        repeat (3) @(posedge dst_clk);
        dst_rst = 0;
    end

    bit test_done = 0;

    // Source-side stimulus: independent reset, then randomized pulses with
    // spacing >= ~3 dst_clk periods (>= 39ns), plus a couple of directed
    // near-minimum-spacing pulses.
    initial begin
        automatic int gap_cycles;
        src_pulse = 0;
        src_rst = 1;
        repeat (3) @(posedge src_clk);
        src_rst = 0;
        @(posedge src_clk);

        // Directed: a few pulses at comfortable spacing first.
        repeat (5) begin
            repeat (12) @(posedge src_clk); // ~84ns gap
            src_pulse = 1;
            @(posedge src_clk);
            src_pulse = 0;
            src_count++;
        end

        // Directed: near-minimum-spacing pulses (~6 src_clk cycles = 42ns > 39ns).
        repeat (4) begin
            repeat (6) @(posedge src_clk); // 42ns gap
            src_pulse = 1;
            @(posedge src_clk);
            src_pulse = 0;
            src_count++;
        end

        // Randomized pulses with generous randomized spacing (>= ~70ns).
        for (int i = 0; i < 60; i++) begin
            gap_cycles = $urandom_range(10, 30); // 70ns to 210ns
            repeat (gap_cycles) @(posedge src_clk);
            src_pulse = 1;
            @(posedge src_clk);
            src_pulse = 0;
            src_count++;
        end

        // Drain time to allow the last pulse's CDC latency to resolve.
        #500;
        test_done = 1;
    end

    initial begin
        wait (test_done == 1);
        #100; // extra margin
        if (dst_count != src_count) begin
            errors++;
            $display("T=%0t ERROR: pulse count mismatch: src_count=%0d dst_count=%0d",
                      $time, src_count, dst_count);
        end

        if (errors == 0) begin
            $display("TEST PASSED");
        end else begin
            $display("TEST FAILED: %0d error(s)", errors);
        end
        $finish;
    end

endmodule
