// =============================================================================
// q3 - Round-Robin Arbiter (3 requesters) -- Testbench
// =============================================================================
// Problem:
//   Implement a round-robin arbiter for 3 requesters. The arbiter keeps a
//   registered 2-bit "pointer" (valid values 0, 1, 2) indicating which
//   requester has top priority THIS cycle.
//
//   Each cycle, gnt is a COMBINATIONAL function of the current req and the
//   current pointer register: scan the 3 requesters starting at "pointer"
//   and wrapping around (order: pointer, (pointer+1)%3, (pointer+2)%3),
//   and grant the FIRST one found with its req bit asserted. gnt is one-hot
//   (or all-zero if req == 3'b000).
//
//   On the next clock edge:
//     - If a grant happened this cycle at index i, pointer <= (i+1) % 3
//       (so the next requester in line gets top priority next cycle).
//     - If req was all-zero this cycle (no grant), pointer holds its value.
//
// Interface:
//   input  logic       clk   : clock
//   input  logic       rst   : synchronous, active-high reset
//   input  logic [2:0] req   : one bit per requester, 1 = requesting
//   output logic [2:0] gnt   : one-hot grant vector (or all-zero), combinational
//                              function of req and the current pointer state
//
// Assumptions / edge-case behavior:
//   - Synchronous active-high reset: on rst, pointer resets to 0 and gnt is 0.
//   - gnt is one-hot: never more than one bit set, all-zero when req==3'b000.
//   - pointer only ever takes values 0, 1, or 2.
//
// This testbench builds a behavioral golden model that tracks "pointer" with
// the exact same update rule and computes expected gnt each cycle from a
// driven sequence of req values (mix of random and directed patterns).
// Compares cycle-by-cycle. Do not edit this file.
// =============================================================================

module q3_tb;

    logic       clk;
    logic       rst;
    logic [2:0] req;
    logic [2:0] gnt;

    int errors = 0;
    int cycle_count = 0;

    q3 dut (
        .clk(clk),
        .rst(rst),
        .req(req),
        .gnt(gnt)
    );

    // Clock generation
    initial clk = 0;
    always #5 clk = ~clk;

    // Watchdog
    initial begin
        #100000;
        $display("TEST FAILED: TIMEOUT");
        $finish;
    end

    // Golden model helper: scan starting at pointer p, wrapping, over req r.
    function automatic [2:0] compute_gnt(input [1:0] p, input [2:0] r);
        compute_gnt = 3'b000;
        for (int k = 0; k < 3; k++) begin
            int idx = (p + k) % 3;
            if (r[idx]) begin
                compute_gnt = 3'b000;
                compute_gnt[idx] = 1'b1;
                return compute_gnt;
            end
        end
        compute_gnt = 3'b000;
    endfunction

    logic [1:0] ptr_golden;
    logic [2:0] exp_gnt;
    logic [1:0] next_ptr;

    task automatic run_cycle(input [2:0] r);
        req = r;
        #1; // allow combinational settle after req changes (driven at negedge)
        exp_gnt = compute_gnt(ptr_golden, req);
        cycle_count++;
        if (gnt !== exp_gnt) begin
            errors++;
            $display("T=%0t ERROR: cycle=%0d ptr=%0d req=%b expected gnt=%b actual gnt=%b",
                      $time, cycle_count, ptr_golden, req, exp_gnt, gnt);
        end
        // Determine next pointer per the spec update rule.
        if (exp_gnt != 3'b000) begin
            for (int i = 0; i < 3; i++) begin
                if (exp_gnt[i]) next_ptr = (i + 1) % 3;
            end
        end else begin
            next_ptr = ptr_golden;
        end
        @(posedge clk);
        ptr_golden = next_ptr;
        @(negedge clk);
    endtask

    initial begin
        req = 3'b000;
        rst = 1;
        ptr_golden = 2'd0;

        // Hold reset for first few edges
        @(posedge clk);
        @(posedge clk);
        @(posedge clk);
        @(negedge clk);
        rst = 0;
        ptr_golden = 2'd0;

        // ---- Directed patterns ----
        // Single requester at a time
        run_cycle(3'b001);
        run_cycle(3'b010);
        run_cycle(3'b100);

        // Idle cycles
        run_cycle(3'b000);
        run_cycle(3'b000);

        // Back-to-back requests from the same requester (req0 keeps asking)
        repeat (5) run_cycle(3'b001);

        // All requesting simultaneously for many cycles -> confirm rotation/fairness
        repeat (12) run_cycle(3'b111);

        // Two requesters alternating
        repeat (6) run_cycle(3'b101);

        // Idle mixed in
        run_cycle(3'b000);
        run_cycle(3'b011);
        run_cycle(3'b000);
        run_cycle(3'b110);

        // Directed: all bits requesting again to re-check rotation continuity
        repeat (9) run_cycle(3'b111);

        // ---- Randomized stimulus ----
        for (int i = 0; i < 300; i++) begin
            run_cycle(3'($urandom_range(0, 7)));
        end

        if (errors == 0) begin
            $display("TEST PASSED");
        end else begin
            $display("TEST FAILED: %0d error(s)", errors);
        end
        $finish;
    end

endmodule
