// =============================================================================
// q20 - "11011" Sequence Detector (Moore FSM, overlapping matches) -- Testbench
// =============================================================================
// Problem:
//   bit_in is a serial bit stream, sampled on every rising clock edge.
//   Detect the pattern 11011 in the stream. OVERLAPPING matches are allowed:
//   e.g. in the stream 1101101..., a match completing at one position can
//   share bits with the start of the next match (the trailing "11" of one
//   match is also the leading "11" of the next potential match).
//
//   Precise timing contract (Moore-style registered output):
//   On the clock edge where bit_in is sampled as the 5th and final bit that
//   completes a 11011 pattern (using overlap with prior bits), detected
//   shall be driven high starting the cycle immediately AFTER that edge,
//   held high for exactly one cycle, then low again (until the next match).
//
// Interface:
//   input  logic clk       : clock
//   input  logic rst       : synchronous, active-high reset
//   input  logic bit_in    : serial input bit, sampled every clock edge
//   output logic detected  : registered (Moore), high for exactly 1 cycle
//                             the cycle after a 11011 match completes
//
// Assumptions / edge-case behavior:
//   - Synchronous active-high reset: on rst, FSM state resets and detected
//     is driven to 0.
//   - Overlapping matches are allowed and must all be detected (e.g. the
//     stream 1101101 contains a match ending at bit index 4 (0-indexed)
//     and, if continued as 1101101101, another overlapping match later).
//   - detected is a registered output: it is never combinationally derived
//     from the same-cycle bit_in; it reflects the match completed on the
//     PREVIOUS clock edge.
//
// Verification strategy: the testbench maintains its own 5-bit shift
// register of the last 5 sampled bit_in values. Each cycle, after shifting
// in the new bit, if the shift register equals 5'b11011 then detected must
// be high on the NEXT cycle (checked then). A long randomized bit stream is
// driven, plus directed patterns (1101101, 1101101101,
// 0000011011000011011) to exercise overlap and multiple matches, checking
// every cycle. Do not edit this file.
// =============================================================================

module q20_tb;

    logic clk;
    logic rst;
    logic bit_in;
    logic detected;

    int errors = 0;
    int cycle_count = 0;

    q20 dut (
        .clk(clk),
        .rst(rst),
        .bit_in(bit_in),
        .detected(detected)
    );

    // Clock generation
    initial clk = 0;
    always #5 clk = ~clk;

    // Watchdog
    initial begin
        #500000;
        $display("TEST FAILED: TIMEOUT");
        $finish;
    end

    logic [4:0] shreg;

    // Per the precise timing contract: on the clock edge where bit_in is
    // sampled as the 5th bit completing a match, detected is driven high
    // for the cycle immediately following THAT SAME edge. So we shift the
    // new bit into shreg and check detected against the resulting match,
    // both right after the same edge that sampled the bit.
    task automatic drive_and_check(input bit b);
        logic exp_detected;
        bit_in = b;
        @(posedge clk);
        #1; // let registered detected settle
        cycle_count++;
        shreg = {shreg[3:0], b};
        exp_detected = (shreg == 5'b11011) ? 1'b1 : 1'b0;
        if (detected !== exp_detected) begin
            errors++;
            $display("T=%0t ERROR: cycle=%0d bit_in=%b shreg=%b expected detected=%b actual detected=%b",
                      $time, cycle_count, b, shreg, exp_detected, detected);
        end
        @(negedge clk);
    endtask

    // Helper to drive a whole directed string, MSB-first char by char.
    task automatic drive_string(input string s);
        for (int i = 0; i < s.len(); i++) begin
            drive_and_check(s[i] == "1");
        end
    endtask

    initial begin
        bit_in = 0;
        rst = 1;
        shreg = 5'b00000;

        @(posedge clk);
        @(posedge clk);
        @(posedge clk);
        @(negedge clk);
        rst = 0;
        shreg = 5'b00000;

        // ---- Directed patterns ----
        drive_string("1101101");            // simple overlap case
        drive_string("1101101101");         // repeated overlap
        drive_string("0000011011000011011"); // multiple isolated + spaced matches
        drive_string("1111111111");          // no matches, all ones (never has the 0s)
        drive_string("0000000000");          // no matches, all zeros
        drive_string("110111011011011");     // dense back-to-back overlaps

        // ---- Randomized bit stream ----
        for (int i = 0; i < 500; i++) begin
            drive_and_check($urandom_range(0, 1));
        end

        // A few more directed patterns after randomization, to make sure
        // state tracking still lines up after a long random run.
        drive_string("11011");
        drive_string("011011");
        drive_string("110110110111011");

        if (errors == 0) begin
            $display("TEST PASSED");
        end else begin
            $display("TEST FAILED: %0d error(s)", errors);
        end
        $finish;
    end

endmodule
