// =============================================================================
// q2 - Fixed-Priority Arbiter (MSB = highest priority) -- Testbench
// =============================================================================
// Problem:
//   Implement a purely combinational fixed-priority arbiter. Given a vector of
//   request signals, grant access to exactly one requester: the one
//   corresponding to the MOST-significant SET bit of req. Priority decreases
//   from bit WIDTH-1 (highest priority) toward bit 0 (lowest priority).
//
// Interface:
//   parameter WIDTH        : number of requesters / width of req and gnt (default 8)
//   input  logic [WIDTH-1:0] req  : one bit per requester, 1 = requesting
//   output logic [WIDTH-1:0] gnt  : one-hot grant vector (or all-zero)
//
// Assumptions / edge-case behavior:
//   - Combinational only: no clk/rst.
//   - If req == 0, gnt == 0 (no grant).
//   - If multiple bits of req are set, exactly ONE bit of gnt is set: the
//     bit at the position of the most-significant '1' in req (bit WIDTH-1
//     wins over bit WIDTH-2, which wins over bit WIDTH-3, etc.).
//   - gnt is otherwise all zero (one-hot output, never more than one bit set).
//
// This testbench is self-checking and exhaustive (WIDTH=8 -> 256 cases),
// plus a handful of directed edge cases. Do not edit this file.
// =============================================================================

module q2_tb;

    localparam WIDTH = 8;

    logic [WIDTH-1:0] req;
    logic [WIDTH-1:0] gnt;

    int errors = 0;

    q2 #(.WIDTH(WIDTH)) dut (
        .req(req),
        .gnt(gnt)
    );

    // Behavioral golden model: isolate the most-significant set bit.
    function automatic [WIDTH-1:0] golden_gnt(input [WIDTH-1:0] r);
        golden_gnt = '0;
        for (int i = WIDTH-1; i >= 0; i--) begin
            if (r[i]) begin
                golden_gnt = (1 << i);
                return golden_gnt;
            end
        end
        golden_gnt = '0;
    endfunction

    task automatic check_case(input [WIDTH-1:0] r);
        logic [WIDTH-1:0] expected;
        req = r;
        #1; // allow combinational settle
        expected = golden_gnt(r);
        if (gnt !== expected) begin
            errors++;
            $display("T=%0t ERROR: req=%b expected gnt=%b actual gnt=%b", $time, r, expected, gnt);
        end
    endtask

    initial begin
        req = '0;

        // Exhaustive sweep over all 256 combinations for WIDTH=8.
        for (int v = 0; v < (1 << WIDTH); v++) begin
            check_case(v[WIDTH-1:0]);
        end

        // Directed edge cases (redundant with exhaustive sweep, but explicit).
        check_case(8'b0000_0000); // no request
        check_case(8'b0000_0001); // bit0 only
        check_case(8'b1000_0000); // bit7 only
        check_case(8'b1111_1111); // all ones -> bit7 wins
        check_case(8'b0101_0101); // bit6 wins
        check_case(8'b0000_0011); // bit1 wins
        check_case(8'b0100_0000); // bit6 only

        if (errors == 0) begin
            $display("TEST PASSED");
        end else begin
            $display("TEST FAILED: %0d error(s)", errors);
        end
        $finish;
    end

endmodule
